name: azodha_todo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  fluttertoast: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
